[SCSB-145] require Python 3.10
spacetelescope/romanisim pull request #106
Opened 2024-03-14 17:53 UTC by zacharyburnett

resolves [SCSB-145](https://jira.stsci.edu/browse/SCSB-145)

propagate Astropy's deprecation of Python 3.9 to downstream packages

> [!NOTE]
> this PR was generated automatically by ``batchpr`` :robot:

2024-03-14 19:23 UTC, PaulHuwe requested changes

2024-03-14 19:23 UTC, PaulHuwe commented on pyproject.toml
> -    # 'rad >=0.18.0',
Can you save the three commented lines here please?

2024-03-15 18:27 UTC, PaulHuwe approved these changes
LGTM

2024-04-17 17:50 UTC, schlafly commented
Sorry, Zach, we didn't merge this back when you submitted it and now it's decayed.  I tried to merge in updates and resolve the conflicts but it looks like I failed.  I think the only real thing that isn't formatting that it's doing now is adding some py311 runners, but maybe I'm missing something.  Can you figure out what you want to do here?

2024-04-17 18:13 UTC, zacharyburnett commented
> Sorry, Zach, we didn't merge this back when you submitted it and now it's decayed. I tried to merge in updates and resolve the conflicts but it looks like I failed. I think the only real thing that isn't formatting that it's doing now is adding some py311 runners, but maybe I'm missing something. Can you figure out what you want to do here?

sure, rebased now onto `main`

2024-04-17 18:32 UTC, merged

2024-04-17 18:32 UTC, schlafly commented
Thanks, merging!