Add some tests of the catalog modules.
spacetelescope/romanisim pull request #20
Opened 2022-11-08 21:44 UTC by schlafly

Add tests on the various catalog routines.

2022-11-09 16:58 UTC, schlafly commented
@PaulHuwe , I had to add a # nosec to make bandit happy---I wanted to use urllib to grab some files from galsim's github repository, and bandit doesn't appear to like the urllib repo.  I don't feel too bad about # nosec in this case---the target link is hard coded, so I am not very worried about users inputting something malicious there.  But I don't know what our policy is.

2022-11-13 23:53 UTC, PaulHuwe requested changes

2022-11-13 23:53 UTC, PaulHuwe commented on romanisim/tests/test_catalog.py
> +    #                            fn.replace('.fits', '_fits.fits'))
Do you want to leave these commented lines here, or should they be cleaned out?

2022-11-13 23:53 UTC, PaulHuwe commented on romanisim/tests/test_catalog.py
> +    print(fits.getdata(fn).dtype)
```suggestion
```

2022-11-13 23:53 UTC, PaulHuwe commented on romanisim/tests/test_catalog.py
> +    from astropy.io import fits
Move the from to the top?

2022-11-13 23:53 UTC, PaulHuwe commented on romanisim/tests/test_catalog.py
> +    print(table.dtype.names)
```suggestion
```

2022-11-14 19:03 UTC, merged